# Generated by Django 4.0.2 on 2022-02-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_product_description_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categories',
        ),
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
