# Generated by Django 4.0.2 on 2022-02-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_rename_category_categories_rename_product_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
